export const industries = [
  "Agtech (Agricultura)",
  "Biotech (Biología y Medicina)",
  "Cleantech (Sostenibilidad Ambiental)",
  "Edtech (Educación)",
  "Fintech (Finanzas)",
  "Healthtech (Cuidado de la Salud)",
  "Insurtech (Seguro)",
  "Legaltech (Legal)",
  "Proptech (Bienes Raíces)",
  "Retailtech (Ventas Minoristas)",
  "Adtech (Publicidad)",
  "Foodtech (Comidas y Bebidas)",
  "Govtech (Gobierno)",
  "Medtech (Dispositivos Médicos)",
  "Martech (Marketing)",
  "Sportstech (Deportes)",
  "Traveltech (Viajes y Turismo)",
  "Ecommerce (Ventas En Línea)",
  "Logistics (Logística)",
  "Gaming (Entretenimiento y Juegos)",
  "Blockchain",
  "AI/ML (Inteligencia Artificial y Machine Learning)",
  "Cybersecurity (Seguridad)",
  "Robotics (Automatización e Ingeniería)",
  "Greentech (Energía Renovable y Sostenibilidad)",
  "SpaceTech (Aeroespacial y Satelites)",
  "Otra",
];
